// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGOVR36dFElZVq5-itZMD5cNv-BNFOnKc',
    appId: '1:539471081307:web:ab63599a2cf6de2400747e',
    messagingSenderId: '539471081307',
    projectId: 'ctrlfirl-2023-24',
    authDomain: 'ctrlfirl-2023-24.firebaseapp.com',
    storageBucket: 'ctrlfirl-2023-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuIgaoo9qUnrSYeWSySPDp4603vxYT0S0',
    appId: '1:539471081307:android:021489ecb819440800747e',
    messagingSenderId: '539471081307',
    projectId: 'ctrlfirl-2023-24',
    storageBucket: 'ctrlfirl-2023-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcmxVYa2wEObihu0B1Y1LoEDwq4WZwWf0',
    appId: '1:539471081307:ios:a193f8f5d1c9f8b900747e',
    messagingSenderId: '539471081307',
    projectId: 'ctrlfirl-2023-24',
    storageBucket: 'ctrlfirl-2023-24.appspot.com',
    iosBundleId: 'com.example.ctrlfirl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcmxVYa2wEObihu0B1Y1LoEDwq4WZwWf0',
    appId: '1:539471081307:ios:f7d858acafaf6fdb00747e',
    messagingSenderId: '539471081307',
    projectId: 'ctrlfirl-2023-24',
    storageBucket: 'ctrlfirl-2023-24.appspot.com',
    iosBundleId: 'com.example.ctrlfirl.RunnerTests',
  );
}
